# app/config/security.yml
security:
    firewalls:
        pctmon:
            pattern: ^/*
            provider: user
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: site_index
            logout:
                path:       logout
                target:     login
            remember_me:
                secret: '%secret%'
                lifetime: 604800
                path: /
    access_control:
      - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: /pctmon/*, roles: [ROLE_ADMIN] }
    providers:
        user:
            entity: { class: PctmonBundle\Entity\User, property: username }
    encoders:
        PctmonBundle\Entity\User: bcrypt