<?php

namespace PctmonBundle\Repository;

/**
 * DestinatariRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DestinatariRepository extends \Doctrine\ORM\EntityRepository
{
}
